<a href="https://colab.research.google.com/github/TerraFusion/pytaf/blob/master/pytaf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install git+https://github.com/TerraFusion/pytaf.git

  Cloning https://github.com/TerraFusion/pytaf.git to /tmp/pip-req-build-crmswgdw
  Stored in directory: /tmp/pip-ephem-wheel-cache-96y4emlm/wheels/89/9a/b7/dbe1239ae21307233b49f0e2c0b9fc92fa251e37d6d1e46624
Successfully built pytaf


In [0]:
import pytaf
import numpy as np

a = np.arange(12, dtype=np.float64).reshape((3,4))
b = a * -333
c = np.arange(3, dtype=np.int32)
print('a value')
print(a)
print('b value')
print(b)
pytaf.clip(a, b, 4)
print('a value after clipping')
print(a)
print('b value before low-level nearest neighbor function')
print(b)
print('Test low-level nearest neighbor with fake ID and numbers of cell')
pytaf.interpolate_nn(a, b, c, 3)
print('b value after low-level nearest neighbor function')
print(b)


a value
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
b value
[[   -0.  -333.  -666.  -999.]
 [-1332. -1665. -1998. -2331.]
 [-2664. -2997. -3330. -3663.]]
a value after clipping
[[   0.    1.    2. -999.]
 [   4.    5.    6.    7.]
 [   8.    9.   10.   11.]]
b value before low-level nearest neighbor function
[[   -0.  -333.  -666.  -999.]
 [-1332. -1665. -1998. -2331.]
 [-2664. -2997. -3330. -3663.]]
Test low-level nearest neighbor with fake ID and numbers of cell
b value after low-level nearest neighbor function
[[ 0.000e+00  1.000e+00  2.000e+00 -9.990e+02]
 [-1.332e+03 -1.665e+03 -1.998e+03 -2.331e+03]
 [-2.664e+03 -2.997e+03 -3.330e+03 -3.663e+03]]
